name: xurmo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  scrollable_positioned_list: ^0.3.8
  dio: ^5.7.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: 6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: 2.4.13
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

